### ISSUE TITLE
unable to follow install instructions - broken links

### ISSUE THREAD

**Issue by ghost** [ssbc/patchfoo#4]
The links for install prerequisites lead to github 404 or 500 errors, unable to install git-ssb or ssb-npm.

Without them the npm install fails, because package.json directly references localhost:8989

**Comment by whoisterencelee** [comment]
In package.json there are references to modules obtained from ssb-git (or is it git-ssb), as I understand its because some development has moved to the git-ssb (it's a good thing to eat own dog food :)

So this means only need to have a scuttlebot installed and listening on the localhost port, and also have git-ssh installed first.

The problem is that without a pub to connect to, I don't think you can get to the git-ssb repositories.

So which pub are we suppose to connect to in order to get to the modules?

**Comment by ghost** [comment]
Yeah, I believe the links in package.json would work if I had the prerequisites installed.. but:
The links I meant are in the Readme under Install: Requirements:
scuttlebot
ssb-npm-registry
git-ssb
These links point to github.com, but clicking them causes *github* error 404 or 500, therefore readers are unable to install prerequisites without googling for them separately. Which is btw another problem, because after such googling I discovered that to install git-ssb I need to have ssb-npm, but ssb-npm is on git-ssb, so.. deadlock.. And https://git.scuttlebot.io has been throwing me 502 Bad Gateway for a couple of weeks (I remember it was working before..)
In effect, in the current state I was not able to install either git-ssb, ssb-npm nor patchfoo

**Comment by whoisterencelee** [comment]
OK, this is how I bootstrapped:
1)  installed scuttlebot
2)  connect to a well-connected pub
3)  follow this instruction:
 http://eight45.net:7718/%25eSY9ewHDPzCJhl%2Bu9hivtWvvjJbSg%2BVmaxyqmvfEfK4%3D.sha256

4) I deviated from the instruction a little bit, and installed the ssb-npm-registry as a plugin by using:

`ssb plugins.install ssb-npm-registry --from="<extracted directory>"`

Seems more clean this way

**Comment by raingloom** [comment]
would it be possible to just, idk... mirror those dependencies??? so people don't have to jump hoops to install patchfoo?
